name: Build and Deploy
on:
  push:
    branches:
      - "master"

jobs:
  Deploy-Contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Test to github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./test/
          target-folder: build-reports/${{ github.sha }}/${{ github.run_id }}/${{ github.run_attempt }}